### PR TITLE
Gg zen

### PR DESCRIPTION
**Pull request by galogarciaiii**
On the README, I've added links to data repositories hosted on Zenodo.

### CODE REVIEW

**Review by taylorreiter — APPROVED** [review]
LGTM. I've removed some empty lines, but it renders fine with them in so up to you if you want to remove or not.

does the github need a new zenodo release with this update?

**Comment by taylorreiter** [comment]
Ok I merged the PR. Where are these changes going to be reflected that they need a new zenodo DOI? is there a new version of the pub that you can point me to?

**Comment by galogarciaiii** [comment]
Thank you, @taylorreiter! Below is the ref to the new release of the corresponding pub.   

Avasthi P, Garcia III G, York R. (2022). Microchamber slide design for cell confinement during imaging. https://doi.org/10.57844/arcadia-z6hb-fs28

Also, I wonder if we could just release a new version of the Zenodo repo to archive this Github repo? https://zenodo.org/records/7015909

**Comment by taylorreiter** [comment]
If the pub isn't being updated, then I don't think the github needs a new release. This info will still be forward facing. We have usually only cut a new release for the repo, and therefore a new zenodo archive, when the pub version is being updated if there are also github changes.

**Comment by galogarciaiii** [comment]
ok, thank you

**Pull request merged**
